### ISSUE TITLE
The gaveup step with compound question type

### ISSUE THREAD

**Issue by pingcheng** [wiris/moodle-qtype_wq#19]
Hi, if the question attempt was gaveup, the step data would not have a filed with answer, and it occurs the displaying issues by an error of "Compound answer index out of bounds." when people do the quiz reviewing (all question in one page).

I am using PHP 7.1 and Moodle 3.4.1+ (build 20180201) with the latest wiris plugin.

Is any existing solution to solve this?

**Comment by pingcheng** [comment]
Thank, @manuelwiris ,
When is your next release for this patch? Cheers

**Comment by manuelwiris** [comment]
@pingcheng 

The issue has been fixed in our latest release #22 

Best regards,

**Comment by manuelwiris** [comment]
@pingcheng 

We are not able to reproduce the issue with our latest version #24. Did you update shortanswerwiris question type or all Wiris Quizzes question types?  qtype_wq should be updated in order to fix the issue. 

If you have the latest version: could you provide us more details about the issue?

Best,
